:sparkles: Guard.Boolean, Guard.Email and Notifications

diff --git a/setup/pre-push b/setup/pre-push
--- a/setup/pre-push
+++ b/setup/pre-push
@@ -10,28 +10,28 @@ YELLOW='\033[1;33m'
 NC='\033[0m' # No Color
 
 echo -e "${YELLOW}Running pre push to dev check...${NC}"
-
 echo -e "${YELLOW}Trying to build tests project...${NC}"
 
-# build the project
-#dotnet build src/Krafted.sln
+# clean / restore / build the project
+dotnet clean "./src/Krafted.sln" --output artifacts
+dotnet restore "./src/Krafted.sln"
+dotnet build "./src/Krafted.sln" --configuration Debug --no-restore -warnaserror
 
-# $? is a shell variable which stores the return code from what we just ran
-#rc=$?
-#if [[ $rc != 0 ]] ; then
-#	echo -e "${RED}Failed to build the project, please fix this and push again${NC}"
-#	echo ""
-#	exit $rc
-#fi
+rb=$?
+if [[ $rb != 0 ]] ; then
+	# A non-zero return code means an error occurred, so tell the user and exit
+	echo -e "${RED}Build failed, please fix and push again${NC}"
+	echo ""
+	exit $rb
+fi
 
 # navigate to the test project to run the tests
 # TODO: change this to your test project directory
-
 echo -e "${YELLOW}Running unit tests...${NC}"
 echo ""
 
 # run the unit tests
-dotnet test src/Krafted.sln
+dotnet test "./src/Krafted.sln"
 
 # $? is a shell variable which stores the return code from what we just ran
 rc=$?
@@ -42,7 +42,7 @@ if [[ $rc != 0 ]] ; then
 	exit $rc
 fi
 
-# Everything went OK so we can exit with a zero
+# everything went OK so we can exit with a zero
 echo -e "${GREEN}Pre push check passed!${NC}"
     echo ""
 
